# Generated by Django 2.2.2 on 2019-06-12 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Duration', models.CharField(max_length=15)),
                ('Months', models.CharField(max_length=10)),
                ('Startdate', models.DateField(max_length=20)),
                ('Enddate', models.DateField(max_length=20)),
                ('Description', models.TextField(max_length=5)),
                ('Teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.Teacher')),
            ],
        ),
    ]
