# Generated by Django 2.2.2 on 2019-06-12 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='Description',
            field=models.TextField(max_length=150),
        ),
    ]
